/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudiocontosRouteImport } from './routes/audiocontos'
import { Route as EscapeRoomsRouteImport } from './routes/escape-rooms'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as PacotesRouteImport } from './routes/pacotes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiocontosRoute = AudiocontosRouteImport.update({
  id: '/audiocontos',
  path: '/audiocontos',
  getParentRoute: () => rootRouteImport,
} as any)
const EscapeRoomsRoute = EscapeRoomsRouteImport.update({
  id: '/escape-rooms',
  path: '/escape-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const PacotesRoute = PacotesRouteImport.update({
  id: '/pacotes',
  path: '/pacotes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiocontos': typeof AudiocontosRoute
  '/escape-rooms': typeof EscapeRoomsRoute
  '/jogos': typeof JogosRoute
  '/pacotes': typeof PacotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiocontos': typeof AudiocontosRoute
  '/escape-rooms': typeof EscapeRoomsRoute
  '/jogos': typeof JogosRoute
  '/pacotes': typeof PacotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audiocontos': typeof AudiocontosRoute
  '/escape-rooms': typeof EscapeRoomsRoute
  '/jogos': typeof JogosRoute
  '/pacotes': typeof PacotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audiocontos' | '/escape-rooms' | '/jogos' | '/pacotes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audiocontos' | '/escape-rooms' | '/jogos' | '/pacotes'
  id:
    '__root__' | '/' | '/audiocontos' | '/escape-rooms' | '/jogos' | '/pacotes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudiocontosRoute: typeof AudiocontosRoute
  EscapeRoomsRoute: typeof EscapeRoomsRoute
  JogosRoute: typeof JogosRoute
  PacotesRoute: typeof PacotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiocontos': {
      id: '/audiocontos'
      path: '/audiocontos'
      fullPath: '/audiocontos'
      preLoaderRoute: typeof AudiocontosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escape-rooms': {
      id: '/escape-rooms'
      path: '/escape-rooms'
      fullPath: '/escape-rooms'
      preLoaderRoute: typeof EscapeRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacotes': {
      id: '/pacotes'
      path: '/pacotes'
      fullPath: '/pacotes'
      preLoaderRoute: typeof PacotesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudiocontosRoute: AudiocontosRoute,
  EscapeRoomsRoute: EscapeRoomsRoute,
  JogosRoute: JogosRoute,
  PacotesRoute: PacotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
